services:
  db:
    image: postgres:15-alpine
    container_name: discord_db
    environment:
      POSTGRES_USER: setyhoseini
      POSTGRES_PASSWORD: setyhoseini
      POSTGRES_DB: discord_clone
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U setyhoseini -d discord_clone"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: discord_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://setyhoseini:setyhoseini@db:5432/discord_clone
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - ENVIRONMENT=development
      - UPLOAD_DIR=uploads
      - PROFILE_DIR=static/profiles
    volumes:
      - ./uploads:/app/uploads
      - ./static:/app/static
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: discord_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: